### ISSUE TITLE
France coverage excludes Lyon

### ISSUE THREAD

**Issue by taniki** [opendatateam/udata#1513]
![screen shot 2018-03-19 at 12 02 35](https://user-images.githubusercontent.com/27315/37591971-8d78778c-2b6d-11e8-864d-97ea97007585.png)

https://www.data.gouv.fr/fr/datasets/delimitation-parcellaire-des-aoc-viticoles-de-linao

**Comment by noirbizarre** [comment]
Fixed in [Geozones `2019.0`](https://github.com/etalab/geozones/releases/tag/2019.0) which is using the proper Etalab geo data (in which France does not have a hole instead of Lyon).

See the same admin page with the new Geozones release: https://www.data.gouv.fr/fr/admin/dataset/5aaf6b7ec751df67b0d7a87f/
