### ISSUE TITLE
udata init suggestions to make it even more powerful

### ISSUE THREAD

**Issue by oncletom** [opendatateam/udata#997]
## Detailed Description

`udata init` is super useful when starting from scratch as it helps developping a theme or having a tour of what udata is.

- [ ] `udata.cfg` populated with sensible defaults and placeholders
- [ ] some topics, users, territories and reuses created by default
- [ ] some users following each other
- [ ] some users being members of organisations
- [ ] some datasets being associated to organisations and territories
- [ ] some datasets being curated on the homepage
- [ ] some reuses being assigned to datasets
- [ ] some reuses being curated on the homepage

## Context

When I develop the udata-etalabfr theme , I want to scratch the database and run `udata init` , so I can develop features and fixes straight away without manually creating users etc.

**Comment by noirbizarre** [comment]
I totally agree but not everything in this proposition is doable right now:
- `udata.cfg` needs to be done at first and if it become the `udata init` responsibility, it means `udata init` needs to prompt for `udata.cfg` parameters and load it once generated because there is no database connexion without `udata.cfg`. It should also not overwrite an existing config if present
- reuses are already generated by `init` command
- topics: easy :+1: 
- users: yes but not many because it means the admin has to clean them itself. There is already one user geneated (i addition to the admin account itself)
- territories: not doable in the current state: territories requires `geozones` to be loaded with some french zones
- users following each others: so at least 2 users, but not many more (still have to clean it manually)
- member of organization: there is an organization generated with the generated user as member
- organization dataset: all generated datasets are already owned by the generated organization
- dataset associated with territories: not possible right now (same reason as fake territories: requires geozones)
- some datasets being curated on home page: should be easy, (`Site.settings.home_datasets`)
- some reuses being assigned to datasets: already done (1 for each dataset, but configurable through the `-r` on the command line)
- some reuses being curated on the homepage: should be easy, (`Site.settings.home_reuses`)

One extra addition could be to ensure that everything is indexed, whether the workers are runing or not (by setting `CELERY_ALWAYS_EAGER` at `True` during the command, this force tasks to be run synchronously)

**Comment by petzlux** [comment]
From my understanding so far, and correct me if I am wrong, `udata init` does some stuff in the background to get the project in a state where you can start using it, like initialise the MongoDB database, Redis cache ... . 

But what is described here is more of a command to create a demo site with example datasets, reuses, users and so on. Isn't this something different that would warrant a different command, for example `udata demo` ?

**Comment by oncletom** [comment]
@petzlux that's a good one indeed.

There are two levels of data population:

1. **first-time install** — website needs to be operated as it would in _production_
1. **developer/designer install** — website needs to have enough data to be able to design/maintain a theme without having to login onto the admin interface

Step 1 should not imply _things_ to be removed prior to be put online whereas Step 2 does not intend to be put somewhere online.

I am unsure if this is something which could be done via a flag (like `--with-demo-data`) or via a dedicated command.

I see some benefits of using a flag as it could be performed in two locations:

- `udata init --with-demo-data`
- `udata reset --with-demo-data` (drop db, init db, populate db, inserts/upserts demo data)

What do you think? Then we could talk again about the scope of both of the commands/flags.
